DROP TABLE IF EXISTS staging_sales;

CREATE TABLE staging_sales (
    IDX INT,
    BOROUGH VARCHAR(50),
    NEIGHBORHOOD VARCHAR(255),
    "BUILDING CLASS CATEGORY" VARCHAR(255),
    "TAX CLASS AT PRESENT" VARCHAR(50),
    BLOCK VARCHAR(50),
    LOT VARCHAR(50),
    EASEMENT VARCHAR(50),
    "BUILDING CLASS AT PRESENT" VARCHAR(255),
    ADDRESS VARCHAR(255),
    "APARTMENT NUMBER" VARCHAR(50),
    "ZIP CODE" VARCHAR(20),
    "RESIDENTIAL UNITS" VARCHAR(50),
    "COMMERCIAL UNITS" VARCHAR(50),
    "TOTAL UNITS" VARCHAR(50),
    "LAND SQUARE FEET" VARCHAR(50),
    "GROSS SQUARE FEET" VARCHAR(50),
    "YEAR BUILT" VARCHAR(50),
    "TAX CLASS AT TIME OF SALE" VARCHAR(50),
    "BUILDING CLASS AT TIME OF SALE" VARCHAR(255),
    "SALE PRICE" VARCHAR(50),
    "SALE DATE" VARCHAR(50)
);

-- ==========================================
-- 2. Load CSV into Staging Table
-- ==========================================
-- Example for Postgres using COPY

\copy staging_sales(IDX, BOROUGH, NEIGHBORHOOD, "BUILDING CLASS CATEGORY", "TAX CLASS AT PRESENT", BLOCK, LOT, EASEMENT, "BUILDING CLASS AT PRESENT", ADDRESS, "APARTMENT NUMBER", "ZIP CODE", "RESIDENTIAL UNITS", "COMMERCIAL UNITS", "TOTAL UNITS", "LAND SQUARE FEET", "GROSS SQUARE FEET", "YEAR BUILT", "TAX CLASS AT TIME OF SALE", "BUILDING CLASS AT TIME OF SALE", "SALE PRICE", "SALE DATE") FROM 'data_processed/nyc-rolling-sales-std-neighborhoods.csv' WITH (FORMAT csv, HEADER true, QUOTE '"', ESCAPE '\');

-- ==========================================
-- 3. Create Clean Table
-- ==========================================

DROP TABLE IF EXISTS clean_sales;
CREATE TABLE clean_sales (
    "INDEX" INT PRIMARY KEY,
    BOROUGH VARCHAR(50),
    NEIGHBORHOOD VARCHAR(255),
    "BUILDING CLASS CATEGORY" VARCHAR(255),
    "TOTAL UNITS" INT,
    "GROSS SQUARE FEET" FLOAT,
    "YEAR BUILT" INT,
    "SALE PRICE" FLOAT,
    "SALE DATE" DATE
);

-- ==========================================
-- 4. Insert Cleaned Data
-- ==========================================

INSERT INTO clean_sales ("INDEX", BOROUGH, NEIGHBORHOOD, "BUILDING CLASS CATEGORY", "TOTAL UNITS",
                         "GROSS SQUARE FEET", "YEAR BUILT", "SALE PRICE", "SALE DATE")
SELECT
    ROW_NUMBER() OVER () AS "INDEX",

    -- Strings: replace '-' with NULL
    CASE TRIM(BOROUGH)
	    WHEN '1' THEN 'MANHATTAN'
	    WHEN '2' THEN 'BRONX'
	    WHEN '3' THEN 'BROOKLYN'
	    WHEN '4' THEN 'QUEENS'
	    WHEN '5' THEN 'STATEN ISLAND'
	    ELSE NULL
	END AS BOROUGH,
    NULLIF(TRIM(NEIGHBORHOOD), '-') AS NEIGHBORHOOD,
    NULLIF(TRIM("BUILDING CLASS CATEGORY"), '-') AS "BUILDING CLASS CATEGORY",

    -- Integers
    CASE WHEN TRIM("TOTAL UNITS") = '-' THEN NULL ELSE CAST("TOTAL UNITS" AS INT) END AS "TOTAL UNITS",

    -- Floats
    CASE WHEN TRIM("GROSS SQUARE FEET") = '-' THEN NULL 
         ELSE CAST(REPLACE(REPLACE("GROSS SQUARE FEET", ',', ''), '$', '') AS FLOAT)
    END AS "GROSS SQUARE FEET",

    -- YEAR BUILT: 0 -> NULL
    CASE 
        WHEN TRIM("YEAR BUILT") = '-' OR TRIM("YEAR BUILT") = '0' THEN NULL
        ELSE CAST("YEAR BUILT" AS INT)
    END AS "YEAR BUILT",

    -- SALE PRICE
    CASE WHEN TRIM("SALE PRICE") = '-' THEN NULL
         ELSE CAST(REPLACE(REPLACE("SALE PRICE", ',', ''), '$', '') AS FLOAT)
    END AS "SALE PRICE",

    -- SALE DATE
    CASE WHEN TRIM("SALE DATE") = '-' THEN NULL
	     ELSE TO_TIMESTAMP("SALE DATE", 'YYYY-MM-DD HH24:MI:SS')::DATE
	END AS "SALE DATE"

FROM staging_sales;
